# .github/Funding.yml
# I’m a free-software advocate: 30% of every donation goes back to other open-source projects,
# and I’ll publish a transparent breakdown of all contributions.

liberapay: 
  - Zoide                         # Liberapay (100% open-source, no fees)